cs499/cs499_app/views/api/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.defaults import *
from django.contrib import admin
admin.autodiscover()

#********* Purpose *********#
# maps the url input to the corresponding function for the url.
# The only one in this file is for handling the POST request

urlpatterns = patterns('',
    # Test
    (r'^post/?$', 'cs499.cs499_app.views.api.post.api_request'), 
)

cs499/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import login, logout
from cs499.cs499_app.views.api.views import display_session
from django.conf.urls.defaults import *

#******** Purpose ********#
# the urlpatterns below will call the associated function when the url pattertern appears

urlpatterns = patterns('',
    url(r'^api/', include('cs499.cs499_app.views.api.urls')),   
    (r'^login/$', 'cs499.cs499_app.views.api.views.login_view'),
    (r'^login/session/$', 'cs499.cs499_app.views.api.views.session_view'),
    (r'^login/session/account/', 'cs499.cs499_app.views.api.views.manageAccount'),   
    url(r'^login/session/(\d+)',  'cs499.cs499_app.views.api.views.display_session'),
    (r'^logout/', 'cs499.cs499_app.views.api.views.logout_view'),  
    (r'^register/$', 'cs499.cs499_app.views.api.views.register'),   
    url(r'^heatmap/',  'cs499.cs499_app.views.api.views.heatmap_view'),
    url(r'^login/session/heatmap(\d+)',  'cs499.cs499_app.views.api.views.display_heatmap'),
    url(r'^login/session/delete(\d+)',  'cs499.cs499_app.views.api.views.delete_session'),    
    (r'^login/session/app/', 'cs499.cs499_app.views.api.views.manageApps'),     
    (r'^login/session/device/', 'cs499.cs499_app.views.api.views.manageDevices'),   
    (r'^login/session/viewdevices/', 'cs499.cs499_app.views.api.views.viewdevices'), 
    (r'^login/session/viewapps/', 'cs499.cs499_app.views.api.views.viewapps'),        
)

cs499/cs499_app/models.py
from django.db import models
from collections import OrderedDict
from datetime import datetime
import json
from django.contrib.auth.models import User
from cs499.cs499_app.views.api.helpers import dejsonify


#******* Purpose ********#
# This file conatins all the models needed for creating tables in the database. 
# Parts of this code was provided to us by our Customer Chris Allen.


# Abstract Models #############################################################

class AbstractBaseModel(models.Model):
    class Meta:
        abstract = True

    # Returns the object represented as a dict.
    def to_dict(self, short=False, deep=False):
        """
        Returns the object represented as a dict. If short is set to true, an
        abbreviated version of the object will be returned (usually just id and
        a any other essential fields, the rest should be omitted).  If deep is
        set to true, the dict will contain child objects, and will assume this
        instance has been annotate with the children objects in a predefined
        attribute.  See the documentation for each model's to_dict() for what
        those attributes should be. Note that sometimes setting short to true
        will cause the attribute that deep enables to be skipped.
        """
        raise NotImplementedError("This model hasn't implemented to_dict().")

    # Returns the object represended as json (based on the value of to_dict())
    def to_json(self):
        return json.dumps(self.to_dict(), sort_keys=False, indent=4)

    # Returns an instance of this model populated with data from the json 
    # string passed in.
    @classmethod
    def create_from_json(cls, json_string, **kwargs):
        instance = cls()
        instance.update_from_json(json_string, **kwargs)
        return instance

    # Returns an instance of this model populated with data from the dict
    # passed in.
    @classmethod
    def create_from_dict(cls, d, **kwargs):
        instance = cls()
        instance.update_from_dict(d, **kwargs)
        return instance

    # Updates this object to match the data in the json passed in.
    def update_from_json(self, json_string, **kwargs):
        d = dejsonify(json_string)
        self.update_from_dict(d, **kwargs)

    # Updates this object to match the data in the dict passed in.
    # If full_clean is true, it'll automatically call self.full_clean() before
    # returning.  If false, validating the model before saving is up to the 
    # caller.
    def update_from_dict(self, d, **kwargs):
        raise NotImplementedError(
            "Ths model hasn't implemented update_from_dict()")



#Device can belong to multiple users but is unique
class Device(AbstractBaseModel):
    serial = models.CharField(max_length = 50, null=False,blank=False,default="0", unique=True)
    version = models.CharField(max_length = 30, null=False,blank=False,default= "0")
    screenHeight = models.IntegerField(null=False, blank= False, default=0)
    screenWidth = models.IntegerField(null=False, blank= False, default=0)
    user = models.ForeignKey(User) 

    def to_dict(self):
        de = OrderedDict()
        de['id'] = self.id;
        de['serial'] = self.serial
        de['version'] = self.version
        de['screenWidth'] = self.screenWidth
        de['screenHeight'] = self.screenHeight
        ge['user'] = self.user

        return de

    def __unicode__(self):
        return "id:{id}, serial:{serial}, version:{version}, screenWidth:{screenWidth}, screenHeight:{screenHeight}, user:{user}".format(
            id = self.id,
            serial = self.serial,
            version = self.version,
            screenWidth = self.screenWidth,
            screenHeight = self.screenHeight,
            user = self.user
        )     

#App can belong to multiple users but is unique
class App(AbstractBaseModel):
    appname = models.CharField(max_length = 100, null=False,blank=False, unique = True)
    user = models.ForeignKey(User) 

    def to_dict(self):
        an = OrderedDict()
        an['id'] = self.id;
        an['appname'] = self.appname
        an['user'] = self.user

        return an

    def __unicode__(self):
        return "id:{id} appname:{appname} user:{user}".format(
            id = self.id,
            appname = self.appname,
            user = self.user
        )           


#Session refers to a collection of motionevents        
class Session(AbstractBaseModel):
    device = models.ForeignKey(Device)
    app = models.ForeignKey(App)
    user = models.ForeignKey(User)
    submission = models.DateTimeField(auto_now_add = True)
   
    def to_dict(self):
        s = OrderedDict()
        s['id'] = self.id      
        s['user'] = self.user
        s['submission'] = self.submission        
        
        return s

    def __unicode__(self):
        return "SessionId:{id} User:{user} Submission:{submission}".format(
            id = self.id,
            user = self.user,            
            submission = self.submission
        )

# Motion event containing all the information for each touch point
class MotionEvent(AbstractBaseModel):
    action     = models.IntegerField(null=False, blank= False, default=0)
    deviceId   = models.IntegerField(null=False, blank= False, default=0)
    downTime   = models.IntegerField(null=False, blank= False, default=0)
    edgeFlags  = models.IntegerField(null=False, blank= False, default=0)
    eventTime  = models.IntegerField(null=False, blank= False, default=0)
    metaState  = models.IntegerField(null=False, blank= False, default=0)
    pressure   = models.IntegerField(null=False, blank= False, default=0)
    size       = models.IntegerField(null=False, blank= False, default=0)
    x          = models.FloatField(null = False, default = 0)
    xPrecision = models.FloatField(null = False, default = 0)
    y          = models.FloatField(null = False, default = 0)
    yPrecision = models.FloatField(null = False, default = 0)
    sessionId  = models.ForeignKey(Session)

    def to_dict(self):
        d = OrderedDict()
        d['id'] = self.id
        d['action'] = self.action
        d['deviceId'] = self.deviceId
        d['downTime'] = self.downTime
        d['edgeFlags'] = self.edgeFlags
        d['eventTime'] = self.eventTime
        d['metaState'] = self.metaState
        d['pressure'] = self.pressure
        d['size'] = self.size
        d['x'] = self.x
        d['xPrecision'] = self.xPrecision
        d['y'] = self.y
        d['yPrecision'] = self.yPrecision
        return d

    def to_heatmap(self):
        h =OrderedDict()
        h['x'] = self.x,
        h['y'] = self.y,
        return h

    def __unicode__(self):
        return "id:{id} action:{action}, deviceId={deviceId}, downTime={downTime}, edgeFlags={edgeFlags}, eventTime={eventTime}, metaStat={metaStat}, pressure={pressure}, size={size}, x:{x}, xPrecision={xPrecision}, y:{y}, yPrecision={yPrecision}".format(
            id = self.id,
            action = self.action,
            deviceId = self.deviceId,
            downTime = self.downTime,
            edgeFlags = self.edgeFlags,
            eventTime = self.eventTime,
            metaStat= self.metaState,
            pressure = self.pressure,
            size = self.size,
            x = self.x,
            xPrecision = self.xPrecision,
            y = self.y,
            yPrecision = self.yPrecision,            
        )

cs499/templates/account.html
{% comment %}
  Page to edit user account
{% endcomment %}

{% block head %}
  <title>Heatmap</title>
{% endblock %}

{% block body %}
  <header>
    <h1>Manage Account</h1>    
  </header>

  <section>
    {% if form.errors %}
      <p>Your username and password didn't match, please try again.</p>
    {% endif %}

    <form method="post" action=".">{% csrf_token %}
      Add application:
      <p>        
        <label for="id_appname">App Name:</label>
        <input type="text" class="text-field" name="appname" placeholder="App"/>
        {{ form.appname }}
      
        {% if next %}
          <input type="hidden" name="next" value="{{ next }}" />
        {% else %}
          <input type="hidden" name="next" value="/session/" />
        {% endif %}
          <input type="submit" value="Add" />  
      </p>    	
    </form>  
  </section>
{% endblock %}

cs499/templates/app.html
{% comment %}
  Page for users to register an app
{% endcomment %}

<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<title>App</title>

<link rel="stylesheet" href="/static/style.css/">
</head>
<body>

{% block body %}
  <header>
    <img src="/static/image/heatmappheader.png" width = "200px" alt="Heatmapp">
    <h1>Register an App</h1>
  </header>

  <section>
    {% if form.errors %}
      <p>There was an error with your input, please try again.</p>
    {% endif %}

    <form  class="app" method="post" action=".">{% csrf_token %}
       <br>
      {{ state }}      
      <br>    
      <p>
        <label for="appname">App Name:</label>
        <input type="text" name="appname" class="text-field" placeholder="App" required="required" />
        {{ form.appname }}
      </p>
      {% if next %}
        <input type="hidden" name="next" value="{{ next }}" />
      {% else %}
        <input type="hidden" name="next" value="/login/" />
      {% endif %}
        <input type="submit" value="Register App" class="button" />
    </form>
    <form class = "viewapp" action="/login/session/viewapps/">
      <input type="submit" value="View Apps" class="button" />
    </form>    
    <form class = "back" action="/login/session/">
      <input type="submit" value="Back" class="button" />
    </form>
    
  </section>
{% endblock %}

cs499/templates/device.html
{% comment %}
  Page for users to register a device
{% endcomment %}

<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<title>App</title>

<link rel="stylesheet" href="/static/style.css/">
</head>
<body>

{% block body %}
  <header>
    <img src="/static/image/heatmappheader.png" width = "200px" alt="Heatmapp">
    <h1>Register a Device</h1>
  </header>

  <section>
    {% if form.errors %}
      <p>There was an error with your input, please try again.</p>
    {% endif %}


    <form  class="device" method="post" action=".">{% csrf_token %}      
      <br>
      {{ state }}
      <br>
      <br>      
        <label for="serial">Serial Number:</label>
        <input type="text" name="serial" class="text-field" placeholder="serial" required="required" />
        {{ form.serial }}
      </p>
      <p>
        <label for="version">Version:</label>
        <input type="text" name="version" class="text-field" placeholder="Version" required="required" />
        {{ form.version }}
      </p>
      <p>
        <label for="screenWidth">Screen Width:</label>
        <input type="text" name="screenWidth" class="text-field" placeholder="Screen Width" required="required" />
        {{ form.screenWidth }}
      </p>
      <p>
        <label for="screenHeight">Screen Height:</label>
        <input type="text" name="screenHeight" class="text-field" placeholder="Screen Height" required="required" />
        {{ form.screenHeight }}
      </p>
      {% if next %}
        <input type="hidden" name="next" value="{{ next }}" />
      {% else %}
        <input type="hidden" name="next" value="/device/" />
      {% endif %}
        <input type="submit" value="Register Device" class="button" />
    </form>
    <form class = "viewapp" action="/login/session/viewdevices/">
      <input type="submit" value="View Devices" class="button" />
    </form>    
    <form class = "back" action="/login/session/">
      <input type="submit" value="Back" class="button" />
    </form>
    <br>    
  </section>
{% endblock %}

cs499/templates/heatmap.html
{% comment %}
  Generates HeatMap of the Users session
{% endcomment %}

<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<title>HeatMap</title>

<link rel="stylesheet" href="/static/style.css/">
<script type="text/javascript" src="/static/jquery-1.9.1.js"></script> 
<script type="text/javascript" src="/static/heatmap/src/heatmap.js"></script>
</head>
<body>
  {% block content %}
  <section>
    <img src="/static/image/heatmappheader.png" width = "200px" alt="Heatmapp">
    <h1>User: {{ session.user.username }} </h1>
    <h2>Session {{ session.id }} </h2>
    <p> </p>
  </section>
{% endblock %}

<script type="text/javascript">
  document.write("<div id='heatmapArea' class = 'heatmapStyle' style='height:"+{{ session.device.screenHeight}}+"px;width:"+{{ session.device.screenWidth}}+"px;'>");
  document.write("<canvas id = 'myCanvas' style='border:3px solid black; z-index: 10000000;'' height='"+{{ session.device.screenHeight}}+"' width='"+{{ session.device.screenWidth}}+"'>");
  document.write("</canvas>");
  document.write("</div>");
</script>



<script type="text/javascript">
window.onload = function(){
  // heatmap configuration
  var config = {
    element: document.getElementById("heatmapArea"),
    radius: 30,
    opacity: 50
  };
  //creates and initializes the heatmap
  var heatmap = h337.create(config);
  var canvas = document.getElementById('myCanvas');
  var context = canvas.getContext('2d');
  var width = {{ session.device.screenWidth}};
  var height = {{ session.device.screenHeight }};
  context.fillStyle = '#ffffff';
  context.fillRect(0,0,width,height);

  var generateData = function(){ 
    var max = 2,
    data = [],
    length = {{ size }},
    width = {{ session.device.screenWidth}},
    height = {{ session.device.screenHeight }};

    {% for m in events %}
        data.push({
        x: {{ m.x }},
        y: {{ m.y }},
        count: 1
      });
    {% endfor %}

    return {
      max: max,
      data: data
    };
  };

  var data = generateData();

  heatmap.store.setDataSet(data);
};
</script>

</body>
</html>

cs499/templates/login.html
{% comment %}
  Main page to authenticate users.
{% endcomment %}

<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<title>Login</title>

<link rel="stylesheet" href="/static/style.css/">
</head>
<body>

{% block body %}  
  <section>
    {% if form.errors %}
      <p>Your username and password didn't match, please try again.</p>
    {% endif %}

    <img class="align-center" src="/static/image/login-logo.png" alt="HeatMapp Logo" title="HeatMapp Logo">

    <form method="POST" action=".">{% csrf_token %}
      <p>
        <label for="id_username">Username:</label>
        <input type="text" class="text-field" placeholder="Username" name="username" required="required" />       
        {{ form.username }}
      </p>
      <p>
        <label for="id_password">Password:</label>
        <input type="password" class="text-field" name="password" placeholder="Password" required="required" />
        {{ form.password }}
      </p>
      {% if next %}
        <input type="hidden" name="next" value="{{ next }}" />
      {% else %}
        <input type="hidden" name="next" value="/session/" />
      {% endif %}
      <input type="submit" class="button" value="Login"/>   
    </form>
    <br>
    <form class = "loginScreen" action="/register/">			           
	   <input type="submit" class="button" value="Register">
  	</form>	
  </section>
{% endblock %}

cs499/templates/logout.html
{% comment %}
  Page to logout users.
{% endcomment %}
<!DOCTYPE html>
<html class="logout_view">

<head>
<meta charset="UTF-8">
<title>Logout</title>
<link rel="stylesheet" href="/static/logout.css/">
<img src="/static/image/heatmappheader.png" width = "200px" alt="Heatmapp">
</head>
<body>	
	<title>Logged out</title>
	<h2>You have successully logged out! <br>
	To return to the login page please click the button below.</h2>	
	<div >
		<form action="/login/">			
			<input type="submit" class="button" value="Home">
		</form>
	</div>

</head>
</html>

cs499/templates/register.html
{% comment %}
  Page for new users to register an account
{% endcomment %}

<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<title>Register</title>

<link rel="stylesheet" href="/static/style.css/">
</head>
<body>

{% block body %}
  <header>
    <img src="/static/image/heatmappheader.png" width = "200px" alt="Heatmapp">
    <h1>Registration Form</h1>
  </header>

  <section>
    {% if form.errors %}
      <p>There was an error with your input, please try again.</p>
    {% endif %}
        
    <form  class="register" method="post" action=".">{% csrf_token %}
      <p>
        <label for="id_username">Username:</label>
        <input type="text" name="username" class="text-field" placeholder="Email" required="required" />
        {{ form.username }}
      </p>
      <p>
        <label for="id_password">Password:</label>
         <input type="password" name="password" class="text-field" placeholder="Password" required="required"  />
        {{ form.password }}
      </p>
      <p>
        <label for="id_firstname">First name:</label>
        <input type="text" name="firstname" class="text-field" placeholder="First Name" required="required" />
        {{ form.firstname }}
      </p>
      <p>
        <label for="id_lastname">Last name:</label>
        <input type="text" name="lastname" class="text-field" placeholder="Last Name" required="required"/>
        {{ form.lastname }}
      </p>      
      {% if next %}
        <input type="hidden" name="next" value="{{ next }}" />        
      {% else %}
        <input type="hidden" name="next" value="/login/" />
      {% endif %}
        <input type="submit" value="Register Account" class="button" />
    </form>
  </section>
{% endblock %}

cs499/templates/session.html
{% comment %}
  Page to show user their sessions.
{% endcomment %}

<!doctype html>
<html class="session_view">
<head>
<meta charset="UTF-8">
<title>Sessions</title>

<link rel="stylesheet" href="/static/session.css/">
</head>
<body>
{% block content %}
  <section>
  	<img src="/static/image/heatmappheader.png" width = "200px" alt="Heatmapp">
    <h2>Welcome {{ user.username }} </h2>
    <p> </p>
  </section>
{% endblock %}

{% block body %}
<section>
	{% if form.errors %}
		<p>You must be logged in to view your sessions.</p>
	{% endif %}

<div style = "width:650px;" >
		<form action="/login/session/app/" style ="display:inline;">		
			<input type="submit" class="button" value="Manage Apps">
		</form>

		<form action="/login/session/device/" style ="display:inline;">		
			<input type="submit" class="button" value="Manage Devices">
		</form>	

		<form action="/logout/" style ="display:inline;">		
			<input type="submit" class="button" value="Logout">
		</form>		
</div>

<br><br><br>
<table class="gradienttable">
<tr>
	<th><p style="padding:0 15px 0 15px"><b> Session </b></p></th>	
	<th><p style="padding:0 15px 0 15px"><b> ID </b></p></th>			
	<th><p style="padding:0 15px 0 15px"><b> Device Serial</b></p></th>	
	<th><p style="padding:0 15px 0 15px"><b> Screen Size </b></p></th>		
	<th><p style="padding:0 15px 0 15px"><b> App Name </b></p></th>	
	<th><p style="padding:0 15px 0 15px"><b> Heatmap View</b></p></th>
	<th><p style="padding:0 15px 0 15px"><b> Submission Time</b></p></th>
	<th><p style="padding:0 15px 0 15px"><b>  </b></p></th>
	<th><p style="padding:0 15px 0 15px"><b> Delete Session</b></p></th>
</tr>
<tr>
	{% for file in data %}
	<tr>			
		<td><p><b>Session_{{ file.id }} </p></td>
		<td><p><b><a href="/login/session/{{ file.id }}" target="_blank">{{ file.id }}</a></p></td>
		<td><p><b>{{ file.device.serial }} </p></td>
		<td><p><b>{{ file.device.screenWidth }}, {{ file.device.screenHeight }} </p></td>
		<td><p><b>{{ file.app.appname }} </p></td>
		<td><p><b><a href="/login/session/heatmap{{ file.id }}" target="_blank"> heatmap_{{file.id }}</a></p></td>
		<td><p><b>{{ file.submission }} </p></td>
		<td><p><b> </p></td>
		<td><p><b><a href="/login/session/delete{{ file.id }}"> delete_{{file.id }} </a></p></td>
	</tr>
	{%endfor%}	
</tr>
</table>	
{% endblock %}
</section>
</html>

cs499/templates/viewapps.html
{% comment %}
  Page to shows users list of their apps.
{% endcomment %}
<!doctype html>
<html class="session_view">
<head>
<meta charset="UTF-8">
<title>View Apps</title>

<link rel="stylesheet" href="/static/session.css/">
</head>
<body>
{% block content %}
  <section>
  	<img src="/static/image/heatmappheader.png" width = "200px" alt="Heatmapp">
    <h2>Welcome {{ user.username }} </h2>
    <p> </p>
  </section>
{% endblock %}

{% block body %}
<section>
	{% if form.errors %}
		<p>You must be logged in to view your sessions.</p>
	{% endif %}

<div style = "width:950px;" >				
    <form class = "back" action="/login/session/app/" style="display:inline;">
      <input type="submit" value="Back" class="button" />
    </form>	
    <form action="/logout/" style ="display:inline;">		
		<input type="submit" class="button" value="Logout">
	</form>  	    
</div>


<br><br><br>
<table class="gradienttable">
<tr>
	<th><p style="padding:0 10px 0 10px"><b> id </b></p></th>
	<th><p style="padding:0 10px 0 10px"><b> Owner </b></p></th>		
	<th><p style="padding:0 10px 0 10px"><b> App Name </b></p></th>	
</tr>
<tr>
	{% for app in apps %}
	<tr>	
		<td><p><b> {{ app.id }} </p></td>
		<td><p><b> {{ app.user }} </p></td>		
		<td><p><b> {{ app.appname }} </p></td>
	</tr>
	{%endfor%}	
</tr>
</table>	
{% endblock %}
</section>
</html>

cs499/templates/viewdevices.html
{% comment %}
  Page to shows users list of their devices.
{% endcomment %}

<!doctype html>
<html class="session_view">
<head>
<meta charset="UTF-8">
<title>View Devices</title>

<link rel="stylesheet" href="/static/session.css/">
</head>
<body>
{% block content %}
  <section>
  	<img src="/static/image/heatmappheader.png" width = "200px" alt="Heatmapp">
    <h2>Welcome {{ user.username }} </h2>
    <p> </p>
  </section>
{% endblock %}

{% block body %}
<section>
	{% if form.errors %}
		<p>You must be logged in to view your sessions.</p>
	{% endif %}

<div style = "width:950px;" >				
    <form class = "back" action="/login/session/device/" style="display:inline;">
      <input type="submit" value="Back" class="button" />
    </form>	
    <form action="/logout/" style ="display:inline;">		
		<input type="submit" class="button" value="Logout">
	</form>  		
</div>

<br><br><br>
<table class="gradienttable">
<tr>
	<th><p style="padding:0 15px 0 15px"><b> Owner </b></p></th>
	<th><p style="padding:0 15px 0 15px"><b> id </b></p></th>	
	<th><p style="padding:0 15px 0 15px"><b> Serial </b></p></th>			
	<th><p style="padding:0 15px 0 15px"><b> Version</b></p></th>	
	<th><p style="padding:0 15px 0 15px"><b> Screen Width </b></p></th>		
	<th><p style="padding:0 15px 0 15px"><b> Screen Height </b></p></th>	
</tr>
<tr>
	{% for device in devices %}
	<tr>	
		<td><p><b>{{ device.user }} </p></td>		
		<td><p><b>Device_{{ device.id }} </p></td>
		<td><p><b>{{ device.serial }} </p></td>
		<td><p><b>{{ device.version }} </p></td>
		<td><p><b>{{ device.screenWidth }} </p></td>
		<td><p><b>{{ device.screenHeight }} </p></td>
		
	</tr>
	{%endfor%}	
</tr>
</table>	
{% endblock %}
</section>
</html>